export const SCREEN = {
  HOME: 'Home',
  DASHBOARD: 'Dashboard',
  LOGIN: 'Login',
  REGISTER: 'Register',
  RECOVERY: 'Recovery',
  CHANGE_PWD: 'Change Password',
  ACCOUNT_INFO: 'Account Info',
  EXPERT_PROFILE: 'Expert-Profile',
  EXPERT_CERTIFICATE: 'Expert-Certificate',
  JOB_LIST: 'Expert-JobList',
  JOB_REQUEST: 'Expert-JobRequest',
  REQUEST_POST: 'Request-Post',
  STATITICS: 'Expert-Statitics',
  CERTIFICATE: 'Certificate',
  CURRENT_REQUEST: 'Current-Request',
  SETTING: 'Setting',
  TRANSACTION_HISTORY: 'Transaction-History',
  FEEDBACK: 'Feedback',
  CREDIT_CARD_MANAGEMENT: 'Credit-Card-Management',
  WITHDRAWAL: 'Withdrawal',
}
